services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-okk
    networks:
      - network-okk
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=okk-api
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  adminer:
    image: adminer:latest
    restart: always
    container_name: adminer-okk
    networks:
      - network-okk
    depends_on:
      - postgres
    ports:
      - '8080:8080'

  redis:
    image: redis:latest
    restart: always
    container_name: redis-okk
    networks:
      - network-okk
    ports:
      - '6379:6379'
    volumes:
      - redis:/data

  nestjs-okk:
    image: restuaar/okk-api:latest
    restart: always
    container_name: okk-api
    depends_on:
      - postgres
      - redis
    networks:
      - network-okk
    ports:
      - '3000:3000'
    env_file:
      - .env

networks:
  network-okk:
    driver: bridge

volumes:
  postgres:
    driver: local
  redis:
    driver: local
