services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: PostgresOKK
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=okk-api
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
    driver: local