services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres-okk
    networks:
      - network-okk
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=okk-api
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - backend_network
    ports:
      - '5050:80'
    depends_on:
      - postgres

  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis-okk
    environment:
      - REDIS_PORT=6379
    networks:
      - network-okk
    ports:
      - '6379:6379'

networks:
  network-okk:
    driver: bridge

volumes:
  postgres_data: {}
  redis:
    driver: local
